### ISSUE TITLE
No linux-hwe-mediatree in ppa for Ubuntu 20.04 Focal Fossa?

### ISSUE THREAD

**Issue by michelalexander** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#106]
I just installed your ppa on Ubuntu 20.04 with HWE, but I failed to install linux-hwe-mediatree because it's not available for Focal Fossa. May I use linux-mediatree instead?

BTW: Thanks for your efforts!

**Comment by shspvr** [comment]
HWE it not out in tell support schedule 20.04.2 you should be using reg install that

**Comment by NumerousHats** [comment]
> HWE it not out in tell support schedule 20.04.2 you should be using reg install that

What does "you should be using reg install that" mean? Use the non-HWE package (i.e. `linux-mediatree`)? Something else?

**Comment by shspvr** [comment]
> > HWE it not out in tell support schedule 20.04.2 you should be using reg install that
> 
> What does "you should be using reg install that" mean? Use the non-HWE package (i.e. `linux-mediatree`)? Something else?

That right the non hwe package

**Comment by mtraxiot** [comment]
can I confirm we should just install linux-mediatree instead of HWE ?
Could someone update the support page for future ?
 https://www.hauppauge.com/pages/support/support_linux.html

**Comment by mtraxiot** [comment]
I've also upgraded to LTS 20.04 and my Quad4 card doesn't appear to be working with MythTV now, however my other cards are..

**Comment by b-rad-NDi** [comment]
There is no HWE kernel for Focal yet. They both use the *exact* same kernel. You install normal linux-mediatree for now.

As for quadHD not working, I have received no such reports. You can make your own issue and post full logs if yours does not.

**Comment by b-rad-NDi** [comment]
Focal HWE kernel 5.8 is incoming in my testing ppa now.
