### ISSUE TITLE
Hauppauge USB-Live2 on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by Blacklion4ever** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#108]
Hello Brad,
I am stuck with dependencies for  linux-mediatree on my jetson nano. I am not comfurtable under Linux, I just followed the readme nevertheless I get error at:

**`$ sudo apt-get install linux-mediatree`**

`Les paquets suivants contiennent des dépendances non satisfaites :`
`linux-mediatree : Dépend: linux-image-4.15.0-108202007061620-generic mais il n'est pas installable`
`Dépend: linux-modules-4.15.0-108202007061620-generic mais il n'est pas installable`
`Dépend: linux-modules-extra-4.15.0-108202007061620-generic mais il n'est pas installable`
`Dépend: linux-headers-4.15.0-108202007061620-generic mais il n'est pas installable`
`E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».`

**Same for `$sudo apt-get install linux-hwe-mediatree`**

`linux-hwe-mediatree : Dépend: linux-image-5.3.0-63202007061620-generic mais il n'est pas installable`
`                       Dépend: linux-modules-5.3.0-63202007061620-generic mais il n'est pas installable`
`                       Dépend: linux-modules-extra-5.3.0-63202007061620-generic mais il n'est pas installable`
`                       Dépend: linux-headers-5.3.0-63202007061620-generic mais il n'est pas installable`

For your information about my release (uname -a and lsb_release -a):

`Linux nano 4.9.140-tegra #1 SMP PREEMPT Thu Jun 25 21:25:44 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux`
`No LSB modules are available.`
`Distributor ID:	Ubuntu`
`Description:	Ubuntu 18.04.4 LTS`
`Release:	18.04`
`Codename:	bionic`

Does the fact I am on jetson nano is a limitation?
Thank you

**Comment by b-rad-NDi** [comment]
If you are not running amd64 or i386 (on older Ubuntu where supported) then you must build the kernel yourself. I don't provide ppa builds for embedded platforms.

For you investigation of the media_build system would be easier. If you have issues then you can file a ticket over there, this is for Ubuntu only.
