### ISSUE TITLE
Recent kernels break ir-keytables

### ISSUE THREAD

**Issue by msorice** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#124]
Kernels in the 5.8 series and in the 5.4 series after 5.4.0-48 break ir-keytables. TOML files in /etc/rc_keymaps are not loaded at boot as they ought to be and were before 5.4.0-48. C.f. [these](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1901089) [posts](https://forum.mythtv.org/viewtopic.php?t=3729&start=30).

**Comment by msorice** [comment]
There exists a [kernel patch](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1901089/comments/28).

**Comment by b-rad-NDi** [comment]
I will apply this patch during the rebuilds I'm working on. Thanks.

**Comment by msorice** [comment]
Outstanding. Thanks so much for your work on this.

M
