### ISSUE TITLE
Support for Ubuntu Server 20.04 LTS HWE with Kernel 5.11 needed

### ISSUE THREAD

**Issue by KaeTuuN** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#130]
Hi all,

I'm using Ubuntu 20.04 LTS with HWE. About three weeks ago HWE switched from Kernel 5.8 to Kernel 5.11 witch is not supported at the moment. Will there be a patch soon?
Do you need any further information?

Greetings

**Comment by b-rad-NDi** [comment]
It's already in my testing ppa. I'll be pushing it to the main ppa by tomorrow.
