### ISSUE TITLE
WinTV-quadHD not recognised on RasPi

### ISSUE THREAD

**Issue by poopingpenis** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#131]
I installed the drivers from the deb files without issue but tvheadend doesn't see the adapter, and lsblk -a doesn't show it either. What do?

**Comment by poopingpenis** [comment]
I got it to recognise when not using my powered USB hub. Problem is, I needed to use it on my Pi with the DualHD so that it wouldn't stop reading data from the adapter when the power draw reached its limit. I'll see how well this works without it for now, though.

**Comment by b-rad-NDi** [comment]
Glad you got it to work. Please re open the issue, or make a new detailed one if you encounter any issue.
