### ISSUE TITLE
linux-hwe-mediatree

### ISSUE THREAD

**Issue by micenusa** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#138]
According to the website:
https://hauppauge.com/pages/support/support_linux.html
I should install the linux-hwe-mediatree version 

the dpkg -l | grep linux-image-generic-hwe response is:
ii  linux-image-generic-hwe-20.04              5.13.0.37.46                               amd64        Generic Linux kernel image

and after I install the PPA, I get:
sudo apt-get install linux-hwe-mediatree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: **Unable to locate package linux-hwe-mediatree**

**Comment by micenusa** [comment]
I'm very new to this linux environment...I assume that I will stick around

**Comment by PSUHammer** [comment]
Are you running Ubuntu?   Did you install v21.10?   I ask as I am curious if you are able to get your tuner working in that scenario.

**Comment by PSUHammer** [comment]
Where do you see that error?  After running `sudo apt-get install linux-mediatree`??

**Comment by shspvr** [comment]
First of all just add PPA
sudo add-apt-repository ppa:b-rad/kernel+mediatree+hauppauge
sudo apt-get update
sudo apt-get install linux-firmware-hauppauge
Then reboot the system
You don't need to install the Install the media tree
This work on Ubuntu 20.04.4 LTS on up

**Comment by micenusa** [comment]
The information on the website is still wrong! 
I will let the issue open until they will gave the correct info on the website!
noob people like me need correct and easy to follow instructions in order to deal with this linux stuf!

**Comment by b-rad-NDi** [comment]
Paste the full contents of the output from these commands:
```
sudo apt-get update
sudo apt-get install linux-hwe-mediatree
```

**Comment by micenusa** [comment]
yeah, thanks..But why there is wrong information on the oficial website?

**Comment by micenusa** [comment]
not important
