### ISSUE TITLE
cx23885[1]: mpeg risc op code error

### ISSUE THREAD

**Issue by micenusa** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#140]
Hi,
I see this cx23885[1]: mpeg risc op code error on the [dmesg](https://docs.google.com/document/d/13R8_cdemMv0OXKWXQR6usYVHEIaJsmWTcQptozySp9g/edit?usp=sharing)!
How to solve it?
I'm running OS: Ubuntu 20.04.4 LTS x86_64 with 5.4.0-107-generic .
I have no video on tvheadend front end apps...

**Comment by b-rad-NDi** [comment]
Have you read through any of the other issues describing this?

**Comment by micenusa** [comment]
Hi, I'm very new to this Linux topic.
If there is already an issue with the solving patch, please close this and redirect me!
btw...In ubuntu 18 it works perfectly...Any version above returns dmesg errors!

**Comment by shspvr** [comment]
> Hi, I'm very new to this Linux topic. If there is already an issue with the solving patch, please close this and redirect me! btw...In ubuntu 18 it works perfectly...Any version above returns dmesg errors!

what your system spec.

**Comment by micenusa** [comment]
not important
