### ISSUE TITLE
`linux-firmware-hauppauge` needed for quadHD in North America

### ISSUE THREAD

**Issue by julianlam** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#141]
Hi @b-rad-NDi &mdash; thank you so much for your work maintaining this firmware. I really appreciate it, and I imagine you don't get a lot of acknowledgement. I apologise for the vague issue report, please close if there's nothing actionable you can take from it.

----

My MythTV box was running fine, and suddenly stopped working (couldn't connect to tuner card, tried VLC, `dvb-fe-tool` couldn't even open the card for reading, etc.) **Most likely** it coincided with an apt upgrade... maybe new linux kernel?

**`uname -a`**
> `Linux media 4.15.0-171202203222222-generic #0+mediatree+hauppauge-Ubuntu SMP Thu Mar 24 18:26:45 UTC x86_64 x86_64 x86_64 GNU/Linux`

*(N.B. yeah this seems likely. This kernel is from 24 Mar, and my recordings stopped on 5 Apr, probably when I ran the dist-upgrade)*

**`lsb_release --codename`**
> `Codename: bionic`

To resolve, I had to install `linux-firmware-hauppauge` as suggested by [the documentation here](https://hauppauge.com/pages/support/support_linux.html#main), even though I am using the quadHD in North America. `linux-firmware-hauppauge` was not installed prior (so it was not a version upgrade)

Let me know if you need me to do anything else to help you debug. I specifically wanted to open an issue because I initially skipped over the "Firmware Install" section because I am in North America and assumed I would not need them because of this note:

> (most North American TV tuners do NOT need firmware to be loaded, so this mainly applies to European/ANZ tuners)

**Comment by b-rad-NDi** [comment]
You've sorted it out. A new commit in the kernel is forcing the tuner firmware to be required when it shouldn't be. For now, you require the firmware installed.
