### ISSUE TITLE
Jammy build

### ISSUE THREAD

**Issue by TelepathicWalrus** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#142]
Hi,

I've recently installed my server to 22.04 from 20.04 and was wondering when you were planning on updating the repository for the new ubuntu? It would be really nice to have TV back :) 

Thanks

**Comment by shspvr** [comment]
what tuner ?

**Comment by b-rad-NDi** [comment]
I have a new Jammy build built, I'll push it to my testing ppa tomorrow.

**Comment by TelepathicWalrus** [comment]
Hey, any update on the build push?

**Comment by pkloehn41** [comment]
Interested as well and thank you for the work to support this hardware for ubuntu. My hardware is the WinTV-quadHD PCIe model.

**Comment by b-rad-NDi** [comment]
If you enable my test ppa Jammy packages are up now. I haven't gotten around to testing them, but they should work.

**Comment by Raithmir** [comment]
Just wanted to confirm Jammy packages appear to be working all OK.

**Comment by b-rad-NDi** [comment]
Thank you, I've pushed them to the main ppa.
