### ISSUE TITLE
quadhd 885 lockup

### ISSUE THREAD

**Issue by mspieth** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#20]
After a while of intermittant use (EIT crawling) on 1 channel (TS1B), the quadhd locks up and is no longer responsive. This affects the paired channel TS2 too. A reboot is required to clear the fault (currently).
logs from cx23885 debug = 7

Sep 30 16:29:05 moonbeam kernel: [14431.513343]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x08008002  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.513346]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.513346]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.513347]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000001  ts1_mask: 0x00001111 count: 0x74c
Sep 30 16:29:05 moonbeam kernel: [14431.513348]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.513348] cx23885: cx23885_irq:  (PCI_MSK_VID_B     0x00000002)
Sep 30 16:29:05 moonbeam kernel: [14431.513349] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.513350] cx23885: cx23885_irq_ts:  (RISCI1            0x00000001)
Sep 30 16:29:05 moonbeam kernel: [14431.513353] cx23885: cx23885_wakeup: [ffff8e3353eb0c00/11] wakeup reg=1868 buf=1868
Sep 30 16:29:05 moonbeam kernel: [14431.513400]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x08000000  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.513401]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.513401]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.513402]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000000  ts1_mask: 0x00001111 count: 0x74c
Sep 30 16:29:05 moonbeam kernel: [14431.513402]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.513403] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.513423] cx23885: cx23885_buf_prepare: cx23885_buf_prepare: ffff8e3353eb0c00
Sep 30 16:29:05 moonbeam kernel: [14431.513426] cx23885: cx23885_buf_queue: [ffff8e3353eb0c00/11] cx23885_buf_queue - append to active
Sep 30 16:29:05 moonbeam kernel: [14431.538386]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x08008002  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.538388]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.538389]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.538389]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000001  ts1_mask: 0x00001111 count: 0x74d
Sep 30 16:29:05 moonbeam kernel: [14431.538390]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.538391] cx23885: cx23885_irq:  (PCI_MSK_VID_B     0x00000002)
Sep 30 16:29:05 moonbeam kernel: [14431.538391] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.538392] cx23885: cx23885_irq_ts:  (RISCI1            0x00000001)
Sep 30 16:29:05 moonbeam kernel: [14431.538395] cx23885: cx23885_wakeup: [ffff8e336906d400/12] wakeup reg=1869 buf=1869
Sep 30 16:29:05 moonbeam kernel: [14431.538438]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x08000000  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.538439]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.538439]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.538440]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000000  ts1_mask: 0x00001111 count: 0x74d
Sep 30 16:29:05 moonbeam kernel: [14431.538441]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.538441] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.538461] cx23885: cx23885_buf_prepare: cx23885_buf_prepare: ffff8e336906d400
Sep 30 16:29:05 moonbeam kernel: [14431.538464] cx23885: cx23885_buf_queue: [ffff8e336906d400/12] cx23885_buf_queue - append to active
Sep 30 16:29:05 moonbeam kernel: [14431.563843]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x08008002  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.563846]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.563847]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.563848]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000001  ts1_mask: 0x00001111 count: 0x74e
Sep 30 16:29:05 moonbeam kernel: [14431.563849]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.563849] cx23885: cx23885_irq:  (PCI_MSK_VID_B     0x00000002)
Sep 30 16:29:05 moonbeam kernel: [14431.563850] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.563851] cx23885: cx23885_irq_ts:  (RISCI1            0x00000001)
Sep 30 16:29:05 moonbeam kernel: [14431.563855] cx23885: cx23885_wakeup: [ffff8e33ca11bc00/13] wakeup reg=1870 buf=1870
Sep 30 16:29:05 moonbeam kernel: [14431.563909]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x08000000  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.563909]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.563910]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.563911]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000000  ts1_mask: 0x00001111 count: 0x74e
Sep 30 16:29:05 moonbeam kernel: [14431.563911]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.563912] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.563937] cx23885: cx23885_buf_prepare: cx23885_buf_prepare: ffff8e33ca11bc00
Sep 30 16:29:05 moonbeam kernel: [14431.563940] cx23885: cx23885_buf_queue: [ffff8e33ca11bc00/13] cx23885_buf_queue - append to active

Sep 30 16:29:05 moonbeam kernel: [14431.588897]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x080c8002  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.588900]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.588901]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.588902]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000001  ts1_mask: 0x00001111 count: 0x74f
Sep 30 16:29:05 moonbeam kernel: [14431.588902]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.588903] cx23885: cx23885_irq:  (PCI_MSK_VID_B     0x00000002)
Sep 30 16:29:05 moonbeam kernel: [14431.588903] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.588904] cx23885: cx23885_irq_ts:  (RISCI1            0x00000001)
Sep 30 16:29:05 moonbeam kernel: [14431.588908] cx23885: cx23885_wakeup: [ffff8e32d7a4ec00/14] wakeup reg=1871 buf=1871
Sep 30 16:29:05 moonbeam kernel: [14431.588959]  ^O^_D: cx23885: cx23885_irq: pci_status: 0x08000000  pci_mask: 0x00001f02
Sep 30 16:29:05 moonbeam kernel: [14431.588961]  ^O^_D: cx23885: cx23885_irq: vida_status: 0x00000000 vida_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.588962]  ^O^_D: cx23885: cx23885_irq: audint_status: 0x00000000 audint_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.588964]  ^O^_D: cx23885: cx23885_irq: ts1_status: 0x00000000  ts1_mask: 0x00001111 count: 0x74f
Sep 30 16:29:05 moonbeam kernel: [14431.588966]  ^O^_D: cx23885: cx23885_irq: ts2_status: 0x00000000  ts2_mask: 0x00000000 count: 0x0
Sep 30 16:29:05 moonbeam kernel: [14431.588967] cx23885: cx23885_irq:  (PCI_MSK_AV_CORE   0x08000000)
Sep 30 16:29:05 moonbeam kernel: [14431.588993] cx23885: cx23885_buf_prepare: cx23885_buf_prepare: ffff8e32d7a4ec00
Sep 30 16:29:05 moonbeam kernel: [14431.588997] cx23885: cx23885_buf_queue: [ffff8e32d7a4ec00/14] cx23885_buf_queue - append to active

interrupts continue until cancel/stop_dma.

notice the pci_status 080c8002 which is unusual. The 000c80000 part is not defined in cx23885-reg.h but obviously something extra happened.
all the bits not masked are also acked at the end of the irq handler which I believe is wrong.

This one has corrupted data but successive uses are ok.

**Comment by mspieth** [comment]
Eventually, valid data stops. Log of setup is the same as before.

Sep 30 20:03:04 moonbeam kernel: [27270.139325] cx23885: cx23885_start_dma: cx23885_start_dma() w: 0, h: 0, f: 0
Sep 30 20:03:04 moonbeam kernel: [27270.139328] cx23885: cx23885_sram_channel_setup: cx23885_sram_channel_setup() Configuring channel [TS1 B]
Sep 30 20:03:04 moonbeam kernel: [27270.139329] cx23885: cx23885_sram_channel_setup: cx23885_sram_channel_setup() 0x00010580 <- 0x00005000
Sep 30 20:03:04 moonbeam kernel: [27270.139330] cx23885: cx23885_sram_channel_setup: cx23885_sram_channel_setup() 0x00010590 <- 0x000052f0
Sep 30 20:03:04 moonbeam kernel: [27270.139331] cx23885: cx23885_sram_channel_setup: cx23885_sram_channel_setup() 0x000105a0 <- 0x000055e0
Sep 30 20:03:04 moonbeam kernel: [27270.139331] cx23885: cx23885_sram_channel_setup: cx23885_sram_channel_setup() 0x000105b0 <- 0x000058d0
Sep 30 20:03:04 moonbeam kernel: [27270.139332] cx23885: cx23885_sram_channel_setup: cx23885_sram_channel_setup() 0x000105c0 <- 0x00005bc0
Sep 30 20:03:04 moonbeam kernel: [27270.139333] cx23885: cx23885_sram_channel_setup: [bridge 885] sram setup TS1 B: bpl=752 lines=5
Sep 30 20:03:04 moonbeam kernel: [27270.139333] cx23885: cx23885[1]: TS1 B - dma channel status dump
Sep 30 20:03:04 moonbeam kernel: [27270.139363] cx23885: cx23885[1]:   cmds: init risc lo   : 0x316f7000
Sep 30 20:03:04 moonbeam kernel: [27270.139390] cx23885: cx23885[1]:   cmds: init risc hi   : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139418] cx23885: cx23885[1]:   cmds: cdt base       : 0x00010580
Sep 30 20:03:04 moonbeam kernel: [27270.139446] cx23885: cx23885[1]:   cmds: cdt size       : 0x0000000a
Sep 30 20:03:04 moonbeam kernel: [27270.139473] cx23885: cx23885[1]:   cmds: iq base        : 0x00010400
Sep 30 20:03:04 moonbeam kernel: [27270.139501] cx23885: cx23885[1]:   cmds: iq size        : 0x00000010
Sep 30 20:03:04 moonbeam kernel: [27270.139529] cx23885: cx23885[1]:   cmds: risc pc lo     : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139556] cx23885: cx23885[1]:   cmds: risc pc hi     : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139584] cx23885: cx23885[1]:   cmds: iq wr ptr      : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139612] cx23885: cx23885[1]:   cmds: iq rd ptr      : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139640] cx23885: cx23885[1]:   cmds: cdt current    : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139668] cx23885: cx23885[1]:   cmds: pci target lo  : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139696] cx23885: cx23885[1]:   cmds: pci target hi  : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139724] cx23885: cx23885[1]:   cmds: line / byte    : 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.139752] cx23885: cx23885[1]:   risc0: 
Sep 30 20:03:04 moonbeam kernel: [27270.139753] 0x00000000 [ INVALID count=0 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139776] cx23885: cx23885[1]:   risc1: 
Sep 30 20:03:04 moonbeam kernel: [27270.139776] 0x00000000 [ INVALID count=0 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139799] cx23885: cx23885[1]:   risc2: 
Sep 30 20:03:04 moonbeam kernel: [27270.139799] 0x00000000 [ INVALID count=0 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139822] cx23885: cx23885[1]:   risc3: 
Sep 30 20:03:04 moonbeam kernel: [27270.139823] 0x00000000 [ INVALID count=0 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139846] cx23885: cx23885[1]:   (0x00010400) iq 0: 
Sep 30 20:03:04 moonbeam kernel: [27270.139846] 0xdc6dcbc0 [ writecr sol eol 22 21 19 18 cnt0 resync 14 count=3008 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139873] cx23885: cx23885[1]:   iq 1: 0x00000000 [ arg #1 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139900] cx23885: cx23885[1]:   iq 2: 0x1c0002f0 [ arg #2 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139926] cx23885: cx23885[1]:   iq 3: 0xdc6dceb0 [ arg #3 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139953] cx23885: cx23885[1]:   (0x00010410) iq 4: 
Sep 30 20:03:04 moonbeam kernel: [27270.139953] 0x00000000 [ INVALID count=0 ]
Sep 30 20:03:04 moonbeam kernel: [27270.139978] cx23885: cx23885[1]:   (0x00010414) iq 5: 
Sep 30 20:03:04 moonbeam kernel: [27270.139979] 0x1c0002f0 [ write sol eol count=752 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140004] cx23885: cx23885[1]:   iq 6: 0xdc6dd1a0 [ arg #1 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140031] cx23885: cx23885[1]:   iq 7: 0x00000000 [ arg #2 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140057] cx23885: cx23885[1]:   (0x00010420) iq 8: 
Sep 30 20:03:04 moonbeam kernel: [27270.140057] 0x1c0002f0 [ write sol eol count=752 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140083] cx23885: cx23885[1]:   iq 9: 0xdc6dd490 [ arg #1 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140109] cx23885: cx23885[1]:   iq a: 0x00000000 [ arg #2 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140136] cx23885: cx23885[1]:   (0x0001042c) iq b: 
Sep 30 20:03:04 moonbeam kernel: [27270.140136] 0x00000000 [ INVALID count=0 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140161] cx23885: cx23885[1]:   (0x00010430) iq c: 
Sep 30 20:03:04 moonbeam kernel: [27270.140162] 0x1c0002f0 [ write sol eol count=752 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140187] cx23885: cx23885[1]:   iq d: 0xdc6dc8d0 [ arg #1 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140214] cx23885: cx23885[1]:   iq e: 0x00000000 [ arg #2 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140240] cx23885: cx23885[1]:   (0x0001043c) iq f: 
Sep 30 20:03:04 moonbeam kernel: [27270.140240] 0x1c0002f0 [ write sol eol count=752 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140266] cx23885: cx23885[1]:   iq 10: 0xc3475ae4 [ arg #1 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140292] cx23885: cx23885[1]:   iq 11: 0xe48cffd0 [ arg #2 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140317] cx23885: cx23885[1]: fifo: 0x00005000 -> 0x6000
Sep 30 20:03:04 moonbeam kernel: [27270.140340] cx23885: cx23885[1]: ctrl: 0x00010400 -> 0x10460
Sep 30 20:03:04 moonbeam kernel: [27270.140366] cx23885: cx23885[1]:   ptr1_reg: 0x00005000
Sep 30 20:03:04 moonbeam kernel: [27270.140391] cx23885: cx23885[1]:   ptr2_reg: 0x00010588
Sep 30 20:03:04 moonbeam kernel: [27270.140416] cx23885: cx23885[1]:   cnt1_reg: 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140441] cx23885: cx23885[1]:   cnt2_reg: 0x00000009
Sep 30 20:03:04 moonbeam kernel: [27270.140464] cx23885: cx23885[1]: risc disasm: ffff8e2ff16f7000 [dma=0x316f7000]
Sep 30 20:03:04 moonbeam kernel: [27270.140500] cx23885: cx23885[1]:   0000: 
Sep 30 20:03:04 moonbeam kernel: [27270.140500] 0x70000000 [ jump count=0 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140521] cx23885: cx23885[1]:   0001: 0x316f700c [ arg #1 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140545] cx23885: cx23885[1]:   0002: 0x00000000 [ arg #2 ]
Sep 30 20:03:04 moonbeam kernel: [27270.140773] cx23885: cx23885_start_dma: cx23885_start_dma() enabling TS int's and DMA
Sep 30 20:03:04 moonbeam kernel: [27270.140780] cx23885: cx23885_start_dma: cx23885_start_dma() initial pci int stat is 0x80f8000
Sep 30 20:03:04 moonbeam kernel: [27270.140801] cx23885: cx23885_start_dma: cx23885_start_dma() initial pci int stat B is 0x080f8000 (0x00000000,0x00001f02)
Sep 30 20:03:04 moonbeam kernel: [27270.140804] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() Register Dump
Sep 30 20:03:04 moonbeam kernel: [27270.140807] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() DEV_CNTRL2               0x00000020
Sep 30 20:03:04 moonbeam kernel: [27270.140810] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() PCI_INT_MSK              0x00001F02
Sep 30 20:03:04 moonbeam kernel: [27270.140813] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() AUD_INT_INT_MSK          0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140816] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() AUD_INT_DMA_CTL          0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140818] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() AUD_EXT_INT_MSK          0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140821] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() AUD_EXT_DMA_CTL          0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140824] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() PAD_CTRL                 0x00500300
Sep 30 20:03:04 moonbeam kernel: [27270.140827] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() ALT_PIN_OUT_SEL          0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140830] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() GPIO2                    0x060966E2
Sep 30 20:03:04 moonbeam kernel: [27270.140833] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() gpcnt(0x00130120)          0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140836] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() gpcnt_ctl(0x00130134)      0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140838] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() dma_ctl(0x00130140)        0x00000011
Sep 30 20:03:04 moonbeam kernel: [27270.140841] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() src_sel(0x00130144)        0x00000001
Sep 30 20:03:04 moonbeam kernel: [27270.140844] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() lngth(0x00130150)          0x000002f0
Sep 30 20:03:04 moonbeam kernel: [27270.140847] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() hw_sop_ctrl(0x00130154)    0x00470bc0
Sep 30 20:03:04 moonbeam kernel: [27270.140850] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() gen_ctrl(0x00130158)       0x0000000c
Sep 30 20:03:04 moonbeam kernel: [27270.140853] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() bd_pkt_status(0x0013015C)  0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140856] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() sop_status(0x00130160)     0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140859] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() fifo_ovfl_stat(0x00130164) 0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140862] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() vld_misc(0x00130168)       0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140865] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() ts_clk_en(0x0013016C)      0x00000001
Sep 30 20:03:04 moonbeam kernel: [27270.140868] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() ts_int_msk(0x00040030)     0x00001111
Sep 30 20:03:04 moonbeam kernel: [27270.140871] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() ts_int_status(0x00040034)  0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140874] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() PCI_INT_STAT           0x080F8000
Sep 30 20:03:04 moonbeam kernel: [27270.140877] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() VID_B_INT_MSTAT        0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140880] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() VID_B_INT_SSTAT        0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140882] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() VID_C_INT_MSTAT        0x00000000
Sep 30 20:03:04 moonbeam kernel: [27270.140885] cx23885: cx23885_tsport_reg_dump: cx23885_tsport_reg_dump() VID_C_INT_SSTAT        0x00000000

except pci_status starts at 0x080F8000

no interrupts occur ever again.

after this even after module unload and reload, the chip is dead until a reboot/reset. This does not need to be a power cycle. It does not affect the other chip on the board.
pci reset (after unload) does not work. Controlled pci power cycle functionality seems disabled and was not tried.

Disabling the iommu in the bios did not help.

**Comment by mspieth** [comment]
I have noticed on failure, 0x40090 and 0x40094 are set to 1 where they were previously 0

Oct  2 09:26:11 moonbeam kernel: [13170.877623] cx23885 0000:27:00.0: cx23885_reg_dump: 00040090: 00000001 00000001 00000000 00000000
Oct  2 09:26:11 moonbeam kernel: [13170.877633] cx23885 0000:27:00.0: cx23885_reg_dump: 000400a0: ffffffff 00000000 00000000 00000000

This is very deterministic. These registers are undocumented in the code as to their purpose.

**Comment by mspieth** [comment]
mega patch that fixes various things

[cx23885-robustness.patch.zip](https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/files/1347664/cx23885-robustness.patch.zip)

**Comment by mspieth** [comment]
now seeing

Oct  3 01:21:48 moonbeam kernel: [70508.943410] cx23885 0000:27:00.0: cx23885_reg_dump: 00040090: 00000001 00000001 00000000 00000000
Oct  3 01:21:48 moonbeam kernel: [70508.943420] cx23885 0000:27:00.0: cx23885_reg_dump: 000400a0: ffffffff 00010000 00000000 00000000

which teh previous method doesnt clear. notice 0x400a4

**Comment by mspieth** [comment]
A new solution to this problem is to delay stop_dma by 20ms + wait for 0x40090/4 not both non zero before completing stop_dma. This has been working for 12h with EIT open/grab/close so this may be a suitable solution. Patch will follow when I am happy. Not there is virtually no delay between one close and the next open (10ms in logs).
Also previous solution to mpeg risc error is not a complete fix. Adding printks does fix it but is not a desirable solution.

**Comment by mspieth** [comment]
Latest reasonably stable patchset including brads set for current media tarball and kernel 4.14.13.
lots of debug on open and close seems to help with ryzen.

[latest_patches_20180126.zip](https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/files/1664098/latest_patches_20180126.zip)

**Comment by b-rad-NDi** [comment]
@mspieth : you have an 885 version of this board, correct? Oddly 0x40090 and 0x40094 are only listed in the cx23888 datasheet. Unfortunately not much documentation past their names: TC_REQ and RC_REQ_SET

You did interpret these correctly though, TC_REQ says it interrupts the RISC engine when set.

**Comment by mspieth** [comment]
@b-rad-NDi : 885 I believe so. see other issue where I posted when you asked for the device.

If you have a datasheet and an NDA you could send an info request to connexant/howmever for clarification on TC_REQ and RC_REQ_SET.

The other choice is to get the source for the windows driver (which you probably have access to as part of hauppauge) and see how things are done there. If not there is always disassembling the windows driver to gain secrets.
If you need analysis help on any of this, let me know but I suspect not.
