### ISSUE TITLE
Frontend missing Type information

### ISSUE THREAD

**Issue by Saentist** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#38]
quadHD (855)
https://cdn.pbrd.co/images/H7tPOHd.png
other brand's
https://cdn.pbrd.co/images/H7tQW2v.png
https://cdn.pbrd.co/images/H7tRWFk.png
something missing

**Comment by b-rad-NDi** [comment]
You find where that 'master for' string is set and I'll get the proper frontend type filled in there. My cursory search just found nothing though.

**Comment by b-rad-NDi** [comment]
You need to tell me exactly what boards these are if I'm expected to figure out differences.

**Comment by b-rad-NDi** [comment]
What utility are you using to view this heirarchy?

**Comment by Saentist** [comment]
This is TVHeadend
----
how to make and install
https://tvheadend.org/boards/4/topics/24116
----
manual for beginners, but good documentation make product attractive  ...
https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/wiki 
oops someting missing ;)

by the way I not see any other device with will not include frontend type DVB-S/C/T
except quadHD
good is that dvb-c and dvb-t have different options
dvb-t have LNA (low noise amplifier) dvb-c hasn't

**Comment by b-rad-NDi** [comment]
Not going to install and debug tvheadend to figure this out.

**Comment by b-rad-NDi** [comment]
Any binary trying to pick a frontend would request the delivery systems supported. They would not be going by a string match.

I have not found a single place that appears to hold this value, so again, what cards are you showing? I can compare the board profile of QuadHD to any other card in cx23885-cards.c and there is zero difference.

**Comment by Saentist** [comment]
https://cdn.pbrd.co/images/H7uqz5G.png
this is Hauppauge WinTV-HVR400

**Comment by b-rad-NDi** [comment]
The formatting is completely different for that entry. I want to know what this is:
https://cdn.pbrd.co/images/H7tRWFk.png

**Comment by Saentist** [comment]
TurboSight TBS 6981 is only cars with i have with cx23885

**Comment by b-rad-NDi** [comment]
Specifically adapter2, since it uses si2168.

**Comment by Saentist** [comment]
https://www.linuxtv.org/wiki/index.php/Silicon_Labs_Si2168

**Comment by b-rad-NDi** [comment]
I am extensively familiar with the si2168. The point is we use that frontend a lot, and in our QuadHD it shows 'master for' and for one of your devices it shows 'DVB-C'.

The TBS6981 appears to only use cx24117, so that is not the device I'm looking for. It's cx23885 board profile is braindead simple too, along with the rest of the support code. I wonder if this is part of the eeprom.

**Comment by b-rad-NDi** [comment]
Ok, fyi this erroneous data is coming directly from tvheadend. tvheadend does some checks and prints 'master for #%d' based on some checks I'm reviewing.

**Comment by b-rad-NDi** [comment]
You should file a ticket with tvheadend about this, I'm not digging further into why they are displaying output the way they do. This is not my bug, unless someone at tvheadend tells me what I'm doing wrong.

**Comment by b-rad-NDi** [comment]
It's related to their lfe_master checks. If lfe_master is set, you get 'master for #%d', if it is not set you get 'DELSYS #%d'

**Comment by b-rad-NDi** [comment]
You may re-open this issue if you get word from tvheaded that this needs anything fixed on my end.

**Comment by Saentist** [comment]
Will add issue

**Comment by Saentist** [comment]
Fixed by TVHeadend team 
changed way how frontend was read
https://github.com/tvheadend/tvheadend/commit/74368d0447b0167e33022d8bf8c46644ddd270ba

**Comment by b-rad-NDi** [comment]
Nice one!
