### ISSUE TITLE
Use dev_info() instead dev_err()

### ISSUE THREAD

**Issue by comio** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#42]
Hi @b-rad-NDi ,

Why do you not use  dev_info() call to show information messages instead dev_err() call?

```
em28xx-cards.c:3798:            dev_err(&intf->dev, "DVB interface %i found:%s%s\n",
```
to
```
em28xx-cards.c:3798:            dev_info(&intf->dev, "DVB interface %i found:%s%s\n",
```
([dev_info() definition](https://elixir.bootlin.com/linux/v4.16/source/include/linux/device.h#L1357))

**Comment by b-rad-NDi** [comment]
Not my doing ;) I tend to only use dev_err and dev_warn when it is an actual error or warning. I'll submit a patch about this issue though, because it does seem strange.

**Comment by comio** [comment]
Perfect. Thanks in advance.

luigi

**Comment by b-rad-NDi** [comment]
Looks like someone beat me to this one.

**Comment by b-rad-NDi** [comment]
Actually this was already upstream when you filed the ticket ;)
