### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by ocha** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#43]
Hi. I was wondering if there are plans to support latest LTS release of Ubuntu in your PPA? 

Thanks.

**Comment by Saentist** [comment]
+1

**Comment by b-rad-NDi** [comment]
This is queued. Trying to work through 'day job duties' and then I'll produce new builds.

**Comment by ocha** [comment]
Thank you @b-rad-NDi ! I appreciate work and support you are putting in this

**Comment by b-rad-NDi** [comment]
Someone upstream broke the second tuner on ATSC DualHD models, a patch for which has been submitted upstream.

The Bionic packages have been mostly qualified now and besides the DualHD issue, appear to be working completely.

**Comment by ocha** [comment]
@b-rad-NDi I have DualHD model. Which version has the path for second tuner fix. I can install it and test it out

**Comment by b-rad-NDi** [comment]
I will start all new builds soon. If you tell me which flavour you prefer I can prioritize it.

**Comment by ocha** [comment]
im on Ubuntu Bionic (18.04). I added PPA but havent installed new kernel since PPA didnt have bionic.. I can install kernel manually and then switch to PPA once available. It's not a pressing issue so I can wait if needed.

**Comment by b-rad-NDi** [comment]
Fully patched packages are up on the dropbox. These have ATSC DualHD fixed.

If you're patient, then I'll be pushing builds to the ppa tomorrow morning.

**Comment by ocha** [comment]
Sounds good. Thank you @b-rad-NDi

**Comment by MikeB2013** [comment]
@b-rad-NDi 
Just for info.

The 4.15.0-20201805041217 build from your dropbox is working well on Xubuntu 18.04 (AMD Ryzen 3 1200 Quad-Core Processor on Gigabyte GA-AB350 Gaming 3 Motherboard, BIOS F22 03/15/2018) with my QuadHD (885) and MythTV Version : v30-Pre-599-gba4c52b

Mike

**Comment by b-rad-NDi** [comment]
Thanks for the update @MikeB2013. I pushed new builds to Launchpad for Xenail, Artful, and Bionic. If they are all successful I will push new virtual packages up to trigger updates.

**Comment by smattord** [comment]
I have funky results on Xubuntu 18.04. In plex the device initially showed up after driver installation but scanning channels became hung and then the device was no longer visible.

**Comment by b-rad-NDi** [comment]
@smattord : if you find problem, then please reproduce, file a new issue, and include an appropriate amount of dmesg. The Bionic packages have been fairly well qualified by us now and no issues were found.

**Comment by b-rad-NDi** [comment]
Bionic virtual packages pushed to Launchpad. 18.04 support is complete. If you find any issues at all, then please file new ticket. Closing this now.
