### ISSUE TITLE
ubuntu 18.10

### ISSUE THREAD

**Issue by asim-vax** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#55]
Will this be supported for 18.10, or does the new kernel contain the patches for live TV and record to work?

**Comment by asim-vax** [comment]
@marathone thanks for responding swiftly :)

**Comment by b-rad-NDi** [comment]
Some devices might still be missing functionality, but 4.17 should contain a significant amount of hauppauge hardware upstreamed. "Bionic" is supported in the PPA, I haven't worked on the Cuttlefish yet, but it will get the same treatment.
