### ISSUE TITLE
HVR-1955 / HVR-1975 devices missing from kernel

### ISSUE THREAD

**Issue by b-rad-NDi** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#63]
Device HVR-1955 and HVR-1975 are old devices, which for antiquated reasons required usage of an NDA driver.

That is a fact no longer. A device found me, and almost nothing was required to get these devices upstream :)

Making this issue so anyone googling might stumble across it.

**Comment by b-rad-NDi** [comment]
Submitted upstream
https://www.spinics.net/lists/linux-media/msg144823.html
Patches added here tomorrow.

**Comment by parkerlreed** [comment]
Calling LG LGDT3306a old... 

*DualHD gasps*

:wink:

**Comment by CvH** [comment]
@b-rad-NDi could you link me the `dvb-tuner-si2157-a30-05.fw` ? I like to include them but google can't find them.

**Comment by b-rad-NDi** [comment]
https://drive.google.com/drive/folders/1ZJCOSd5cxfbVqCFtZ4A06HzrWN9h6cmJ?usp=sharing
I extracted the si2157 firmware from a Hauppauge driver.

**Comment by b-rad-NDi** [comment]
Series accepted.
Pull request issued to media tree kernel maintainer :D

**Comment by b-rad-NDi** [comment]
pull request merged :)

**Comment by b-rad-NDi** [comment]
@cvh : when if/you backport the upstreamed series be sure to note the change in firmware name due to maintainer comment.

**Comment by CvH** [comment]
@b-rad-NDi tx, I have a look
