### ISSUE TITLE
HVR-1265 - drivers upstream?

### ISSUE THREAD

**Issue by chrsmrtnx** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#66]
Question more than an issue:

Are the drivers for the WinTV-HVR-1265 in the upstream Linux kernels, or would I still need to patch and build a custom kernel? This would be for ATSC. I'll be running 4.19, which is slated to be released with Debian Buster in a few months.

Thanks.

**Comment by b-rad-NDi** [comment]
Unsure what kernel versions 1265 was mainlined, but I imagine digital support is in 4.19.
