### ISSUE TITLE
Ubuntu 18.04 LTS (Bionic) released a new HWE kernel: 5.0.0

### ISSUE THREAD

**Issue by sindastra** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#81]
Ubuntu 18.04 LTS (Bionic) released a new HWE kernel: 5.0.0

Please update accordingly, thanks.

**Comment by b-rad-NDi** [comment]
Hi, issues are being sorted out. If you'd like to test please see my staging repo:
https://launchpad.net/~b-rad/+archive/ubuntu/test-test-hw-staging/

**Comment by b-rad-NDi** [comment]
This is installable and boots fine, but is still untested, on the above linked ppa.

**Comment by sindastra** [comment]
What kind of testing is required?

**Comment by b-rad-NDi** [comment]
Just stating that Hauppauge testers have not run through and validated hardware. There's nothing that should have broken, so everything should still be ok.

**Comment by sindastra** [comment]
I will try to test it tomorrow.

**Comment by sindastra** [comment]
I just wanted to go ahead and test it on my end and added the testing repo. I hoped it would simply prompt to upgrade the kernel but it did not. How would I install the testing kernel?

**Comment by b-rad-NDi** [comment]
I'll add virtual package for you, that should trigger the upgrade.

**Comment by sindastra** [comment]
I feel stupid now to ask but:

```
# apt list --upgradable
Listing... Done
linux-hwe-headers-mediatree/bionic,bionic 0.18.9+bionic all [upgradable from: 0.18.8+bionic]
linux-hwe-image-mediatree/bionic,bionic 0.18.9+bionic all [upgradable from: 0.18.8+bionic]
```
but then:
```
# apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```
And yes I did ```apt update``` beforehand.

**Comment by b-rad-NDi** [comment]
Unsure, I use apt-get still.

**Comment by sindastra** [comment]
I merely meant to say that somehow the update isn't happening. Maybe something wrong with the virtual package?

**Comment by b-rad-NDi** [comment]
fudge, you're correct. There's missing tags in the package names. Unsure how that happened.

**Comment by b-rad-NDi** [comment]
Should be good to go now.

**Comment by sindastra** [comment]
Works on my end, thanks! 👍
