### ISSUE TITLE
WinTV-HVR-1265 Does not recognized 

### ISSUE THREAD

**Issue by sonu-rana** [b-rad-NDi/Ubuntu-media-tree-kernel-builder#85]
I have installed the drivers from https://www.hauppauge.com/support  for ubuntu 16.04
After that I restarted the system 
the output of uname -a is this 

Linux sonu 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

does not show mediatree as you can see so please help me.

**Comment by b-rad-NDi** [comment]
You're not running this kernel, when you run uname -a it should include mediatree+hauppauge in the output. If you refresh and dist-upgrade you should be running the correct version, otherwise you'll have to drop into grub and manually select it.
